export const IS_AUTHTHENTICATED = 'IS_AUTHTHENTICATED'

export const SET_USER = 'SET_USER' 

export const SET_BOOK = "SET_BOOK"
export const ERROR_BOOK = "ERR0R_BOOK"

export const SETUSER_BOOK = "SETUSER_BOOK"
export const ERRORUSER_BOOK = "ERR0RUSER_BOOK"

export const SET_TUTORIAL = 'SET_TUTORIAL'
export const ERROR_TUTORIAL = 'ERROR_TUTORIAL'

export const SETUSER_TUTORIAL = 'SETUSER_TUTORIAL'
export const ERRORUSER_TUTORIAL = 'ERRORUSER_TUTORIAL'

export const SET_DOCUMENTS = 'SET_DOCUMENTS'
export const ERROR_DOCUMENTS = 'ERROR_DOCUMENTS'